package com.fba.app.domain.model

object SangharakshitaData {

    private data class Entry(val catNum: String, val title: String, val year: Int, val imageUrl: String)

    private val entries: List<Entry> = listOf(
        Entry("S02", "Larger Sukhavativyuha Sutra, The", 0, "https://www.freebuddhistaudio.com/images/talks/S02.jpg"),
        Entry("11", "Arising of the Bodhichitta, The", 1965, "https://www.freebuddhistaudio.com/images/talks/11.jpg"),
        Entry("116", "Buddha’s Philosophy of Right Speech, The", 1965, "https://www.freebuddhistaudio.com/m/medium/YzFHh3wLCAE7.jpg"),
        Entry("06", "Buddhism and the Bishop of Woolwich", 1965, "https://www.freebuddhistaudio.com/images/talks/06.jpg"),
        Entry("15", "Direct Pointing to the Mind of Man, A", 1965, "https://www.freebuddhistaudio.com/images/talks/15.jpg"),
        Entry("09", "Going for Refuge", 1965, "https://www.freebuddhistaudio.com/images/talks/09.jpg"),
        Entry("04", "Heights and Depths in the Spiritual Life, The", 1965, "https://www.freebuddhistaudio.com/images/talks/04.jpg"),
        Entry("92", "Lamas of Tibet, The", 1965, "https://www.freebuddhistaudio.com/images/talks/92.jpg"),
        Entry("14", "No Dependence on Words and Letters", 1965, "https://www.freebuddhistaudio.com/images/talks/14.jpg"),
        Entry("16", "Seeing Into One’s Own Nature and Realising Buddhahood", 1965, "https://www.freebuddhistaudio.com/images/talks/16.jpg"),
        Entry("13", "Special Transmission Outside the Scriptures, A", 1965, "https://www.freebuddhistaudio.com/m/medium/NpaHFAIDpVSA.jpg"),
        Entry("10", "Stream Entry", 1965, "https://www.freebuddhistaudio.com/images/talks/10.jpg"),
        Entry("12", "Turning About in the Deepest Seat of Consciousness, The", 1965, "https://www.freebuddhistaudio.com/images/talks/12.jpg"),
        Entry("19", "Approach to Buddhism, The", 1966, "https://www.freebuddhistaudio.com/images/talks/19.jpg"),
        Entry("23", "Buddha, God, and Reality, The", 1966, "https://www.freebuddhistaudio.com/images/talks/23.jpg"),
        Entry("22", "Buddha: Man or Superman?, The", 1966, "https://www.freebuddhistaudio.com/images/talks/22.jpg"),
        Entry("117", "Buddhism and Psychoanalysis", 1966, "https://www.freebuddhistaudio.com/images/talks/117.jpg"),
        Entry("37", "Buddhism and the Language of Myth", 1966, "https://www.freebuddhistaudio.com/images/talks/37.jpg"),
        Entry("07", "Buddhism and the New Reformation", 1966, "https://www.freebuddhistaudio.com/images/talks/07.jpg"),
        Entry("20", "Buddhism in England", 1966, "https://www.freebuddhistaudio.com/images/talks/20.jpg"),
        Entry("24", "Dynamics of Being, The", 1966, "https://www.freebuddhistaudio.com/images/talks/24.jpg"),
        Entry("21", "Evolution: Lower and Higher", 1966, "https://www.freebuddhistaudio.com/images/talks/21.jpg"),
        Entry("08", "Introducing Buddhism", 1966, "https://www.freebuddhistaudio.com/images/talks/08.jpg"),
        Entry("17", "Is Religion Necessary?", 1966, "https://www.freebuddhistaudio.com/images/talks/17.jpg"),
        Entry("27", "Mystery of the Void, The", 1966, "https://www.freebuddhistaudio.com/images/talks/27.jpg"),
        Entry("26", "Nirvana", 1966, "https://www.freebuddhistaudio.com/images/talks/26.jpg"),
        Entry("30", "Pattern of Buddhist Life and Work, The", 1966, "https://www.freebuddhistaudio.com/images/talks/30.jpg"),
        Entry("29", "Spiritual Community, The", 1966, "https://www.freebuddhistaudio.com/images/talks/29.jpg"),
        Entry("34", "Stages of the Spiritual Path (Reprised), The", 1966, "https://www.freebuddhistaudio.com/images/talks/34.jpg"),
        Entry("28", "Stages of the Spiritual Path, The", 1966, "https://www.freebuddhistaudio.com/images/talks/28.jpg"),
        Entry("25", "Texture of Reality, The", 1966, "https://www.freebuddhistaudio.com/images/talks/25.jpg"),
        Entry("18", "Why Buddhism?", 1966, "https://www.freebuddhistaudio.com/images/talks/18.jpg"),
        Entry("40", "Analytical Psychology of the Abhidharma, The", 1967, "https://www.freebuddhistaudio.com/images/talks/40.jpg"),
        Entry("43", "Archetypal Symbolism in the Biography of the Buddha", 1967, "https://www.freebuddhistaudio.com/images/talks/43.jpg"),
        Entry("42", "Depth Psychology of the Yogachara, The", 1967, "https://www.freebuddhistaudio.com/images/talks/42.jpg"),
        Entry("73", "Heart Sutra, The", 1967, "https://www.freebuddhistaudio.com/images/talks/73.jpg"),
        Entry("45", "Mandala: Tantric Symbol of Integration, The", 1967, "https://www.freebuddhistaudio.com/images/talks/45.jpg"),
        Entry("33", "Meditation: the Expanding Consciousness", 1967, "https://www.freebuddhistaudio.com/images/talks/33.jpg"),
        Entry("31", "Mind: Reactive and Creative", 1967, "https://www.freebuddhistaudio.com/images/talks/31.jpg"),
        Entry("35", "Poetry and Devotion in Buddhism: the Sevenfold Puja", 1967, "https://www.freebuddhistaudio.com/images/talks/35.jpg"),
        Entry("44", "Psycho-Spiritual Symbolism in the Tibetan Book of the Dead", 1967, "https://www.freebuddhistaudio.com/images/talks/44.jpg"),
        Entry("41", "Psychology of Spiritual Development, The", 1967, "https://www.freebuddhistaudio.com/images/talks/41.jpg"),
        Entry("46", "Zen and the Psychotherapeutic Process", 1967, "https://www.freebuddhistaudio.com/images/talks/46.jpg"),
        Entry("52", "Conscious Evolution of Man: Right Effort, The", 1968, "https://www.freebuddhistaudio.com/images/talks/52.jpg"),
        Entry("57", "Dalai Lama: His Reincarnations, The", 1968, "https://www.freebuddhistaudio.com/images/talks/57.jpg"),
        Entry("38", "FWBO Sevenfold Puja, The", 1968, "https://www.freebuddhistaudio.com/images/talks/38.jpg"),
        Entry("60", "Four Foundation Yogas of the Tibetan Buddhist Tantra, The", 1968, "https://www.freebuddhistaudio.com/images/talks/60.jpg"),
        Entry("62", "Future of Tibetan Buddhism, The", 1968, "https://www.freebuddhistaudio.com/images/talks/62.jpg"),
        Entry("55", "How Buddhism Came to Tibet", 1968, "https://www.freebuddhistaudio.com/images/talks/55.jpg"),
        Entry("51", "Ideal Society: Right Livelihood, The", 1968, "https://www.freebuddhistaudio.com/images/talks/51.jpg"),
        Entry("49", "Ideal of Human Communication: Right Speech, The", 1968, "https://www.freebuddhistaudio.com/images/talks/49.jpg"),
        Entry("53", "Levels of Awareness: Right Mindfulness", 1968, "https://www.freebuddhistaudio.com/images/talks/53.jpg"),
        Entry("02", "Meaning of the Dharma, The", 1968, "https://www.freebuddhistaudio.com/m/medium/l7iBHMnSYx7A.jpg"),
        Entry("58", "Monks and Laymen in Buddhist Tibet", 1968, "https://www.freebuddhistaudio.com/images/talks/58.jpg"),
        Entry("05", "Nature and Development of Buddhism, The", 1968, "https://www.freebuddhistaudio.com/images/talks/05.jpg"),
        Entry("47", "Nature of Existence: Right Understanding, The", 1968, "https://www.freebuddhistaudio.com/images/talks/47.jpg"),
        Entry("50", "Principles of Ethics: Right Action, The", 1968, "https://www.freebuddhistaudio.com/images/talks/50.jpg"),
        Entry("36", "Psychology of Buddhist Ritual, The", 1968, "https://www.freebuddhistaudio.com/images/talks/36.jpg"),
        Entry("48", "Reason and Emotion in the Spiritual Life: Right Resolve", 1968, "https://www.freebuddhistaudio.com/m/medium/D2lIjT43eFMz.jpg"),
        Entry("54", "Samadhi, the Higher Consciousness: Right Meditation", 1968, "https://www.freebuddhistaudio.com/images/talks/54.jpg"),
        Entry("03", "Sangha or Buddhist Community, The", 1968, "https://www.freebuddhistaudio.com/m/medium/DNCp4E8TxbUO.jpg"),
        Entry("56", "Schools of Tibetan Buddhism", 1968, "https://www.freebuddhistaudio.com/images/talks/56.jpg"),
        Entry("59", "Symbols of Tibetan Buddhist Art", 1968, "https://www.freebuddhistaudio.com/images/talks/59.jpg"),
        Entry("61", "Tibetan Buddhist Meditation", 1968, "https://www.freebuddhistaudio.com/images/talks/61.jpg"),
        Entry("01", "Who is the Buddha?", 1968, "https://www.freebuddhistaudio.com/m/medium/aD8WETvOBGm7.jpg"),
        Entry("69", "'Masculinity' and 'Femininity' in the Spiritual Life", 1969, "https://www.freebuddhistaudio.com/images/talks/69.jpg"),
        Entry("68", "Altruism and Individualism in the Spiritual Life", 1969, "https://www.freebuddhistaudio.com/images/talks/68.jpg"),
        Entry("77", "Art and the Spiritual Life", 1969, "https://www.freebuddhistaudio.com/images/talks/77.jpg"),
        Entry("66", "Awakening of the Bodhi Heart, The", 1969, "https://www.freebuddhistaudio.com/images/talks/66.jpg"),
        Entry("76", "Axial Age and the Emergence of the ‘New Man’, The", 1969, "https://www.freebuddhistaudio.com/images/talks/76.jpg"),
        Entry("71", "Bodhisattva Hierarchy, The", 1969, "https://www.freebuddhistaudio.com/images/talks/71.jpg"),
        Entry("67", "Bodhisattva Vow, The", 1969, "https://www.freebuddhistaudio.com/images/talks/67.jpg"),
        Entry("63", "Breaking Through into Buddhahood", 1969, "https://www.freebuddhistaudio.com/images/talks/63.jpg"),
        Entry("72", "Buddha and the Bodhisattva: Eternity and Time, The", 1969, "https://www.freebuddhistaudio.com/images/talks/72.jpg"),
        Entry("79", "Buddhism and the Path of the Higher Evolution", 1969, "https://www.freebuddhistaudio.com/images/talks/79.jpg"),
        Entry("82", "Buddhism, Nietzsche, and the ‘Superman’", 1969, "https://www.freebuddhistaudio.com/images/talks/82.jpg"),
        Entry("81", "Cosmic Significance of the Bodhisattva Ideal, The", 1969, "https://www.freebuddhistaudio.com/images/talks/81.jpg"),
        Entry("74", "Diamond Sutra, The", 1969, "https://www.freebuddhistaudio.com/images/talks/74.jpg"),
        Entry("75", "Evolution: Lower and Higher", 1969, "https://www.freebuddhistaudio.com/images/talks/75.jpg"),
        Entry("64", "Heroic Ideal in Buddhism, The", 1969, "https://www.freebuddhistaudio.com/images/talks/64.jpg"),
        Entry("70", "On the Threshold of Enlightenment", 1969, "https://www.freebuddhistaudio.com/images/talks/70.jpg"),
        Entry("65", "Origin and Development of the Bodhisattva Ideal, The", 1969, "https://www.freebuddhistaudio.com/images/talks/65.jpg"),
        Entry("78", "Religion: Ethnic and Universal", 1969, "https://www.freebuddhistaudio.com/images/talks/78.jpg"),
        Entry("80", "Stream Entry: the Point of No Return", 1969, "https://www.freebuddhistaudio.com/images/talks/80.jpg"),
        Entry("93", "Buddha’s Philosophy of Personal Relations, The", 1970, "https://www.freebuddhistaudio.com/images/talks/93.jpg"),
        Entry("84", "From Alienated Awareness to Integrated Awareness", 1970, "https://www.freebuddhistaudio.com/images/talks/84.jpg"),
        Entry("83", "How Consciousness Evolves", 1970, "https://www.freebuddhistaudio.com/images/talks/83.jpg"),
        Entry("89", "Individual and the Spiritual Community, The", 1970, "https://www.freebuddhistaudio.com/images/talks/89.jpg"),
        Entry("85", "Individuality, True and False", 1970, "https://www.freebuddhistaudio.com/images/talks/85.jpg"),
        Entry("90", "Is a Guru Necessary?", 1970, "https://www.freebuddhistaudio.com/images/talks/90.jpg"),
        Entry("32", "Karma and Rebirth", 1970, "https://www.freebuddhistaudio.com/images/talks/32.jpg"),
        Entry("87", "Meditation Versus Psychotherapy", 1970, "https://www.freebuddhistaudio.com/images/talks/87.jpg"),
        Entry("88", "Problem of Human Relationships, The", 1970, "https://www.freebuddhistaudio.com/images/talks/88.jpg"),
        Entry("86", "Question of Psychological Types, The", 1970, "https://www.freebuddhistaudio.com/images/talks/86.jpg"),
        Entry("102", "Archetype of the Divine Healer, The", 1971, "https://www.freebuddhistaudio.com/images/talks/102.jpg"),
        Entry("96", "Drama of Cosmic Enlightenment, The", 1971, "https://www.freebuddhistaudio.com/images/talks/96.jpg"),
        Entry("94", "Evolution or Extinction: Current World Problems", 1971, "https://www.freebuddhistaudio.com/images/talks/94.jpg"),
        Entry("100", "Five Element Symbolism and the Stupa", 1971, "https://www.freebuddhistaudio.com/images/talks/100.jpg"),
        Entry("91", "Individual, the Group, and the Community, The", 1971, "https://www.freebuddhistaudio.com/images/talks/91.jpg"),
        Entry("101", "Jewel in the Lotus, The", 1971, "https://www.freebuddhistaudio.com/images/talks/101.jpg"),
        Entry("98", "Myth of the Return Journey, The", 1971, "https://www.freebuddhistaudio.com/images/talks/98.jpg"),
        Entry("99", "Symbols of Life and Growth", 1971, "https://www.freebuddhistaudio.com/m/medium/VTdjZB0SCNiA.jpg"),
        Entry("97", "Transcending the Human Predicament", 1971, "https://www.freebuddhistaudio.com/images/talks/97.jpg"),
        Entry("95", "Universal Perspective of Mahayana Buddhism, The", 1971, "https://www.freebuddhistaudio.com/images/talks/95.jpg"),
        Entry("115", "Meaning of Parinirvana, The", 1972, "https://www.freebuddhistaudio.com/images/talks/115.jpg"),
        Entry("113", "New Man Speaks, The", 1972, "https://www.freebuddhistaudio.com/images/talks/113.jpg"),
        Entry("111", "Padmasambhava: Tantric Guru of Tibet", 1972, "https://www.freebuddhistaudio.com/images/talks/111.jpg"),
        Entry("109", "Symbolism of Colours and Mantric Sound, The", 1972, "https://www.freebuddhistaudio.com/images/talks/109.jpg"),
        Entry("108", "Symbolism of Offerings and Self-Sacrifice, The", 1972, "https://www.freebuddhistaudio.com/images/talks/108.jpg"),
        Entry("106", "Symbolism of the Cosmic Refuge Tree and the Archetypal Guru, The", 1972, "https://www.freebuddhistaudio.com/images/talks/106.jpg"),
        Entry("107", "Symbolism of the Cremation Ground and the Celestial Maidens, The", 1972, "https://www.freebuddhistaudio.com/images/talks/107.jpg"),
        Entry("110", "Symbolism of the Five Buddhas, ‘Male’ and ‘Female’, The", 1972, "https://www.freebuddhistaudio.com/images/talks/110.jpg"),
        Entry("105", "Symbolism of the Sacred Thunderbolt or Diamond Sceptre of the Lamas, The", 1972, "https://www.freebuddhistaudio.com/images/talks/105.jpg"),
        Entry("103", "Symbolism of the Tibetan Wheel of Life, The", 1972, "https://www.freebuddhistaudio.com/images/talks/103.jpg"),
        Entry("104", "Tantric Symbolism of the Stupa, The", 1972, "https://www.freebuddhistaudio.com/images/talks/104.jpg"),
        Entry("112", "Way to Enlightenment, The", 1972, "https://www.freebuddhistaudio.com/images/talks/112.jpg"),
        Entry("114", "Word of the Buddha, The", 1972, "https://www.freebuddhistaudio.com/images/talks/114.jpg"),
        Entry("118", "Path of Regular Steps and the Path of Irregular Steps, The", 1974, "https://www.freebuddhistaudio.com/images/talks/118.jpg"),
        Entry("119", "Enlightenment as Experience and as Non-Experience", 1975, "https://www.freebuddhistaudio.com/images/talks/119.jpg"),
        Entry("120", "Ideal of Human Enlightenment, The", 1975, "https://www.freebuddhistaudio.com/images/talks/120.jpg"),
        Entry("122", "Meaning of Spiritual Community, The", 1975, "https://www.freebuddhistaudio.com/images/talks/122.jpg"),
        Entry("121", "What Meditation Really Is", 1975, "https://www.freebuddhistaudio.com/images/talks/121.jpg"),
        Entry("134", "Blueprint for a New World, A", 1976, "https://www.freebuddhistaudio.com/images/talks/134.jpg"),
        Entry("124", "Bodhisattva’s Dream, The", 1976, "https://www.freebuddhistaudio.com/m/medium/lxVyKH4YpgBk.jpg"),
        Entry("127", "Buddhism and Culture", 1976, "https://www.freebuddhistaudio.com/images/talks/127.jpg"),
        Entry("129", "Buddhist Economics", 1976, "https://www.freebuddhistaudio.com/images/talks/129.jpg"),
        Entry("123", "Growth of a Mahayana Sutra, The", 1976, "https://www.freebuddhistaudio.com/images/talks/123.jpg"),
        Entry("131", "Method of Personal Development, A", 1976, "https://www.freebuddhistaudio.com/images/talks/131.jpg"),
        Entry("130", "Moral Order and its Upholders, The", 1976, "https://www.freebuddhistaudio.com/images/talks/130.jpg"),
        Entry("128", "Nature, Man, and Enlightenment", 1976, "https://www.freebuddhistaudio.com/images/talks/128.jpg"),
        Entry("133", "Nucleus of a New Society, The", 1976, "https://www.freebuddhistaudio.com/images/talks/133.jpg"),
        Entry("126", "Protectors of the Dharma, The", 1976, "https://www.freebuddhistaudio.com/images/talks/126.jpg"),
        Entry("125", "Spiritual Significance of Confession, The", 1976, "https://www.freebuddhistaudio.com/images/talks/125.jpg"),
        Entry("132", "Vision of Human Existence, A", 1976, "https://www.freebuddhistaudio.com/images/talks/132.jpg"),
        Entry("137", "Levels of Going for Refuge", 1978, "https://www.freebuddhistaudio.com/images/talks/137.jpg"),
        Entry("135", "System of Meditation, A", 1978, "https://www.freebuddhistaudio.com/images/talks/135.jpg"),
        Entry("136", "Vision of History, A", 1978, "https://www.freebuddhistaudio.com/images/talks/136.jpg"),
        Entry("138", "Authority and the Individual in the New Society", 1979, "https://www.freebuddhistaudio.com/images/talks/138.jpg"),
        Entry("144", "Building the Buddha Land", 1979, "https://www.freebuddhistaudio.com/images/talks/144.jpg"),
        Entry("142", "Commitment and Spiritual Community", 1979, "https://www.freebuddhistaudio.com/images/talks/142.jpg"),
        Entry("150", "Four Great Reliances: Criteria for the Spiritual Life, The", 1979, "https://www.freebuddhistaudio.com/images/talks/150.jpg"),
        Entry("147", "History Versus Myth in Man’s Quest for Meaning", 1979, "https://www.freebuddhistaudio.com/images/talks/147.jpg"),
        Entry("140", "Individual and the World Today, The", 1979, "https://www.freebuddhistaudio.com/images/talks/140.jpg"),
        Entry("143", "Magic of a Mahayana Sutra, The", 1979, "https://www.freebuddhistaudio.com/images/talks/143.jpg"),
        Entry("149", "Mystery of Human Communication, The", 1979, "https://www.freebuddhistaudio.com/images/talks/149.jpg"),
        Entry("145", "On Being All Things to All Men", 1979, "https://www.freebuddhistaudio.com/images/talks/145.jpg"),
        Entry("151", "Padmasambhava Talk", 1979, "https://www.freebuddhistaudio.com/images/talks/151.jpg"),
        Entry("139", "Taste of Freedom, The", 1979, "https://www.freebuddhistaudio.com/images/talks/139.jpg"),
        Entry("146", "Transcendental Critique of Religion, The", 1979, "https://www.freebuddhistaudio.com/images/talks/146.jpg"),
        Entry("148", "Way of Non-Duality, The", 1979, "https://www.freebuddhistaudio.com/images/talks/148.jpg"),
        Entry("141", "Western Buddhists and Eastern Buddhism", 1979, "https://www.freebuddhistaudio.com/images/talks/141.jpg"),
        Entry("152", "Case of Dysentry, A", 1982, "https://www.freebuddhistaudio.com/images/talks/152.jpg"),
        Entry("154", "Dimensions of Going for Refuge", 1982, "https://www.freebuddhistaudio.com/images/talks/154.jpg"),
        Entry("155", "Fidelity", 1982, "https://www.freebuddhistaudio.com/images/talks/155.jpg"),
        Entry("157", "India Talk", 1982, "https://www.freebuddhistaudio.com/images/talks/157.jpg"),
        Entry("156", "Between Twin Sala Trees", 1983, "https://www.freebuddhistaudio.com/images/talks/156.jpg"),
        Entry("159", "Bodhisattva Principle, The", 1983, "https://www.freebuddhistaudio.com/images/talks/159.jpg"),
        Entry("160", "Ex-Untouchable Indian Buddhists, The", 1983, "https://www.freebuddhistaudio.com/images/talks/160.jpg"),
        Entry("158", "Launching of the New Mitrata, The", 1983, "https://www.freebuddhistaudio.com/images/talks/158.jpg"),
        Entry("LOC1117", "Order Puja Led by Bhante Sangharakshita", 1983, "https://www.freebuddhistaudio.com/m/uKp8bNgbigXw.jpg"),
        Entry("153", "Wreath of Blue Lotuses, A", 1983, "https://www.freebuddhistaudio.com/images/talks/153.jpg"),
        Entry("162", "Buddhism, World Peace, and Nuclear War", 1984, "https://www.freebuddhistaudio.com/images/talks/162.jpg"),
        Entry("163", "Journey to Il Convento, The", 1984, "https://www.freebuddhistaudio.com/images/talks/163.jpg"),
        Entry("164", "St. Jerome Revisited", 1984, "https://www.freebuddhistaudio.com/images/talks/164.jpg"),
        Entry("161", "Ten Pillars of Buddhism, The", 1984, "https://www.freebuddhistaudio.com/images/talks/161.jpg"),
        Entry("P04", "Caves of Bhaja, The", 1985, "https://www.freebuddhistaudio.com/images/talks/P04.jpg"),
        Entry("165", "Glory of the Literary World, The", 1985, "https://www.freebuddhistaudio.com/images/talks/165.jpg"),
        Entry("166", "Buddhist Dawn in the West", 1986, "https://www.freebuddhistaudio.com/images/talks/166.jpg"),
        Entry("P01", "Conquering New Worlds", 1986, "https://www.freebuddhistaudio.com/images/talks/P01.jpg"),
        Entry("167", "Discerning the Buddha", 1986, "https://www.freebuddhistaudio.com/images/talks/167.jpg"),
        Entry("39", "Western Buddhist Order Ordination Ceremony, A", 1986, "https://www.freebuddhistaudio.com/images/talks/39.jpg"),
        Entry("169", "Buddha's Victory, The", 1987, "https://www.freebuddhistaudio.com/images/talks/169.jpg"),
        Entry("168", "Twenty Years on the Middle Way", 1987, "https://www.freebuddhistaudio.com/images/talks/168.jpg"),
        Entry("171", "History of My Going for Refuge, The", 1988, "https://www.freebuddhistaudio.com/images/talks/171.jpg"),
        Entry("170", "Next Twenty Years, The", 1988, "https://www.freebuddhistaudio.com/images/talks/170.jpg"),
        Entry("P03", "Autobiographical Sequence of Poems, An", 1990, "https://www.freebuddhistaudio.com/images/talks/P03.jpg"),
        Entry("P02", "Hercules and the Birds", 1990, "https://www.freebuddhistaudio.com/images/talks/P02.jpg"),
        Entry("176", "My Eight Main Teachers", 1990, "https://www.freebuddhistaudio.com/images/talks/176.jpg"),
        Entry("172", "My Relation to the Order", 1990, "https://www.freebuddhistaudio.com/images/talks/172.jpg"),
        Entry("LOC2451", "Sangharakshita - Reading Poems About Friendship", 1990, "https://www.freebuddhistaudio.com/m/uKp8bNgbigXw.jpg"),
        Entry("P05", "Cave, The", 1991, "https://www.freebuddhistaudio.com/images/talks/P05.jpg"),
        Entry("175", "Dilgo Khyentse Rimpoche", 1991, "https://www.freebuddhistaudio.com/images/talks/175.jpg"),
        Entry("LOC2529", "Evening with Sangharakshita: Facing Mount Kanchenjunga, An", 1991, "https://www.freebuddhistaudio.com/m/medium/w2uKrTRZ2OmM.jpg"),
        Entry("174", "Five Pillars of the FWBO, The", 1991, "https://www.freebuddhistaudio.com/images/talks/174.jpg"),
        Entry("173", "Message of Dhardo Rimpoche, The", 1991, "https://www.freebuddhistaudio.com/images/talks/173.jpg"),
        Entry("LOC931", "Three Jewels: The Central Ideals of Buddhism - Part 1, The", 1991, "https://www.freebuddhistaudio.com/m/medium/U8b2dHcjstwU.jpg"),
        Entry("LOC929", "Three Jewels: The Central Ideals of Buddhism - Part 2, The", 1991, "https://www.freebuddhistaudio.com/m/medium/U8b2dHcjstwU.jpg"),
        Entry("LOC937", "Three Jewels: The Central Ideals of Buddhism - Part 3, The", 1991, "https://www.freebuddhistaudio.com/m/medium/U8b2dHcjstwU.jpg"),
        Entry("LOC933", "Three Jewels: The Central Ideals of Buddhism - Part 4, The", 1991, "https://www.freebuddhistaudio.com/m/medium/U8b2dHcjstwU.jpg"),
        Entry("LOC934", "Three Jewels: The Central Ideals of Buddhism - Part 5, The", 1991, "https://www.freebuddhistaudio.com/m/medium/U8b2dHcjstwU.jpg"),
        Entry("LOC935", "Three Jewels: The Central Ideals of Buddhism - Part 6, The", 1991, "https://www.freebuddhistaudio.com/m/medium/U8b2dHcjstwU.jpg"),
        Entry("LOC936", "Three Jewels: The Central Ideals of Buddhism - Part 7, The", 1991, "https://www.freebuddhistaudio.com/m/medium/U8b2dHcjstwU.jpg"),
        Entry("DE02", "Integration of Buddhism into Western Society (Die Integration des Buddhismus in die Westliche Gesellschaft), The", 1992, "https://www.freebuddhistaudio.com/images/talks/DE02.jpg"),
        Entry("DE01", "Meaning of Friendship in Buddhism (Die Bedeutung von Freundschaft im Buddhismus), The", 1992, "https://www.freebuddhistaudio.com/m/medium/w7N8VIMIh9DT.jpg"),
        Entry("180", "Fifteen Points for Old and New Order Members", 1993, "https://www.freebuddhistaudio.com/images/talks/180.jpg"),
        Entry("181", "Rain of the Dharma, The", 1993, "https://www.freebuddhistaudio.com/images/talks/181.jpg"),
        Entry("179", "Wisdom Beyond Words", 1993, "https://www.freebuddhistaudio.com/images/talks/179.jpg"),
        Entry("LOC866", "Wisdom Beyond Words: The Buddhist Vision of Ultimate Reality - Part 1", 1993, "https://www.freebuddhistaudio.com/m/medium/vb8pb0c43GED.jpg"),
        Entry("LOC867", "Wisdom Beyond Words: The Buddhist Vision of Ultimate Reality - Part 2", 1993, "https://www.freebuddhistaudio.com/m/medium/vb8pb0c43GED.jpg"),
        Entry("LOC868", "Wisdom Beyond Words: The Buddhist Vision of Ultimate Reality - Part 3", 1993, "https://www.freebuddhistaudio.com/m/medium/vb8pb0c43GED.jpg"),
        Entry("LOC869", "Wisdom Beyond Words: The Buddhist Vision of Ultimate Reality - Part 4", 1993, "https://www.freebuddhistaudio.com/m/medium/vb8pb0c43GED.jpg"),
        Entry("LOC870", "Wisdom Beyond Words: The Buddhist Vision of Ultimate Reality - Part 5", 1993, "https://www.freebuddhistaudio.com/m/medium/vb8pb0c43GED.jpg"),
        Entry("LOC871", "Wisdom Beyond Words: The Buddhist Vision of Ultimate Reality - Part 6", 1993, "https://www.freebuddhistaudio.com/m/medium/vb8pb0c43GED.jpg"),
        Entry("LOC872", "Wisdom Beyond Words: The Buddhist Vision of Ultimate Reality - Part 7", 1993, "https://www.freebuddhistaudio.com/m/medium/vb8pb0c43GED.jpg"),
        Entry("LOC873", "Wisdom Beyond Words: The Buddhist Vision of Ultimate Reality - Part 8", 1993, "https://www.freebuddhistaudio.com/m/medium/vb8pb0c43GED.jpg"),
        Entry("183", "Disappearing Buddha, The", 1994, "https://www.freebuddhistaudio.com/images/talks/183.jpg"),
        Entry("182", "Fifteen Points for Buddhist Parents", 1994, "https://www.freebuddhistaudio.com/images/talks/182.jpg"),
        Entry("185", "Transcendental Eightfold Path, The", 1994, "https://www.freebuddhistaudio.com/images/talks/185.jpg"),
        Entry("184", "Twenty-Four Nidanas, The", 1994, "https://www.freebuddhistaudio.com/images/talks/184.jpg"),
        Entry("186", "Great Buddhists of the 20th Century", 1995, "https://www.freebuddhistaudio.com/images/talks/186.jpg"),
        Entry("188", "Extending the Hand of Fellowship", 1996, "https://www.freebuddhistaudio.com/images/talks/188.jpg"),
        Entry("LOC979", "In The Sign of the Golden Wheel: Indian Memoirs of an English Buddhist - Part 1", 1996, "https://www.freebuddhistaudio.com/m/medium/U3V4GeIotB1r.jpg"),
        Entry("LOC988", "In The Sign of the Golden Wheel: Indian Memoirs of an English Buddhist - Part 10", 1996, "https://www.freebuddhistaudio.com/m/medium/U3V4GeIotB1r.jpg"),
        Entry("LOC990", "In The Sign of the Golden Wheel: Indian Memoirs of an English Buddhist - Part 11", 1996, "https://www.freebuddhistaudio.com/m/medium/U3V4GeIotB1r.jpg"),
        Entry("LOC980", "In The Sign of the Golden Wheel: Indian Memoirs of an English Buddhist - Part 2", 1996, "https://www.freebuddhistaudio.com/m/medium/U3V4GeIotB1r.jpg"),
        Entry("LOC981", "In The Sign of the Golden Wheel: Indian Memoirs of an English Buddhist - Part 3", 1996, "https://www.freebuddhistaudio.com/m/medium/U3V4GeIotB1r.jpg"),
        Entry("LOC982", "In The Sign of the Golden Wheel: Indian Memoirs of an English Buddhist - Part 4", 1996, "https://www.freebuddhistaudio.com/m/medium/U3V4GeIotB1r.jpg"),
        Entry("LOC983", "In The Sign of the Golden Wheel: Indian Memoirs of an English Buddhist - Part 5", 1996, "https://www.freebuddhistaudio.com/m/medium/U3V4GeIotB1r.jpg"),
        Entry("LOC984", "In The Sign of the Golden Wheel: Indian Memoirs of an English Buddhist - Part 6", 1996, "https://www.freebuddhistaudio.com/m/medium/U3V4GeIotB1r.jpg"),
        Entry("LOC985", "In The Sign of the Golden Wheel: Indian Memoirs of an English Buddhist - Part 7", 1996, "https://www.freebuddhistaudio.com/m/medium/U3V4GeIotB1r.jpg"),
        Entry("LOC986", "In The Sign of the Golden Wheel: Indian Memoirs of an English Buddhist - Part 8", 1996, "https://www.freebuddhistaudio.com/m/medium/U3V4GeIotB1r.jpg"),
        Entry("LOC987", "In The Sign of the Golden Wheel: Indian Memoirs of an English Buddhist - Part 9", 1996, "https://www.freebuddhistaudio.com/m/medium/U3V4GeIotB1r.jpg"),
        Entry("187", "Intellect, Emotion, and Will", 1996, "https://www.freebuddhistaudio.com/images/talks/187.jpg"),
        Entry("LOC1029", "Rainbow Road From Tooting Broadway to Kalimpong, Memoirs of an English Buddhist - Part 2, The", 1997, "https://www.freebuddhistaudio.com/m/medium/qlYbkgDhfiOd.jpg"),
        Entry("LOC1031", "Rainbow Road From Tooting Broadway to Kalimpong, Memoirs of an English Buddhist - Part 3, The", 1997, "https://www.freebuddhistaudio.com/m/medium/qlYbkgDhfiOd.jpg"),
        Entry("LOC1032", "Rainbow Road From Tooting Broadway to Kalimpong, Memoirs of an English Buddhist - Part 4, The", 1997, "https://www.freebuddhistaudio.com/m/medium/qlYbkgDhfiOd.jpg"),
        Entry("LOC1035", "Rainbow Road:  From Tooting Broadway to Kalimpong, Memoirs of an English Buddhist - Part 7, The", 1997, "https://www.freebuddhistaudio.com/m/medium/qlYbkgDhfiOd.jpg"),
        Entry("LOC1030", "Rainbow Road: From Tooting Broadway to Kalimpong, Memoirs of an English Buddhist - Part 1, The", 1997, "https://www.freebuddhistaudio.com/m/medium/qlYbkgDhfiOd.jpg"),
        Entry("LOC1119", "Rainbow Road: From Tooting Broadway to Kalimpong, Memoirs of an English Buddhist - Part 10, The", 1997, "https://www.freebuddhistaudio.com/m/medium/qlYbkgDhfiOd.jpg"),
        Entry("LOC1120", "Rainbow Road: From Tooting Broadway to Kalimpong, Memoirs of an English Buddhist - Part 11, The", 1997, "https://www.freebuddhistaudio.com/m/medium/qlYbkgDhfiOd.jpg"),
        Entry("LOC1033", "Rainbow Road: From Tooting Broadway to Kalimpong, Memoirs of an English Buddhist - Part 5, The", 1997, "https://www.freebuddhistaudio.com/m/medium/qlYbkgDhfiOd.jpg"),
        Entry("LOC1034", "Rainbow Road: From Tooting Broadway to Kalimpong, Memoirs of an English Buddhist - Part 6, The", 1997, "https://www.freebuddhistaudio.com/m/medium/qlYbkgDhfiOd.jpg"),
        Entry("LOC1036", "Rainbow Road: From Tooting Broadway to Kalimpong, Memoirs of an English Buddhist - Part 8, The", 1997, "https://www.freebuddhistaudio.com/m/medium/qlYbkgDhfiOd.jpg"),
        Entry("LOC1118", "Rainbow Road: From Tooting Broadway to Kalimpong, Memoirs of an English Buddhist - Part 9, The", 1997, "https://www.freebuddhistaudio.com/m/medium/qlYbkgDhfiOd.jpg"),
        Entry("189", "Reflections on Going Forth", 1997, "https://www.freebuddhistaudio.com/images/talks/189.jpg"),
        Entry("LOC922", "Drama of Cosmic Enlightenment: Parables, Myths and Symbols of the White Lotus Sutra - Part 1, The", 1998, "https://www.freebuddhistaudio.com/m/medium/CbUpw6Wj1QFL.jpg"),
        Entry("LOC923", "Drama of Cosmic Enlightenment: Parables, Myths and Symbols of the White Lotus Sutra - Part 2, The", 1998, "https://www.freebuddhistaudio.com/m/medium/CbUpw6Wj1QFL.jpg"),
        Entry("LOC924", "Drama of Cosmic Enlightenment: Parables, Myths and Symbols of the White Lotus Sutra - Part 3, The", 1998, "https://www.freebuddhistaudio.com/m/medium/CbUpw6Wj1QFL.jpg"),
        Entry("LOC925", "Drama of Cosmic Enlightenment: Parables, Myths and Symbols of the White Lotus Sutra - Part 4, The", 1998, "https://www.freebuddhistaudio.com/m/medium/CbUpw6Wj1QFL.jpg"),
        Entry("LOC927", "Drama of Cosmic Enlightenment: Parables, Myths and Symbols of the White Lotus Sutra - Part 5, The", 1998, "https://www.freebuddhistaudio.com/m/medium/CbUpw6Wj1QFL.jpg"),
        Entry("LOC926", "Drama of Cosmic Enlightenment: Parables, Myths and Symbols of the White Lotus Sutra - Part 6, The", 1998, "https://www.freebuddhistaudio.com/m/medium/CbUpw6Wj1QFL.jpg"),
        Entry("LOC1942", "Fragen und Antworten im Buddhistischen Zentrum Essen 1998", 1998, "https://www.freebuddhistaudio.com/m/uKp8bNgbigXw.jpg"),
        Entry("LOC1020", "Bodhisattva Ideal: Wisdom and Compassion in Buddhism - Part 1, The", 1999, "https://www.freebuddhistaudio.com/m/medium/XeougS4OEKle.jpg"),
        Entry("LOC1021", "Bodhisattva Ideal: Wisdom and Compassion in Buddhism - Part 2, The", 1999, "https://www.freebuddhistaudio.com/m/medium/XeougS4OEKle.jpg"),
        Entry("LOC1022", "Bodhisattva Ideal: Wisdom and Compassion in Buddhism - Part 3, The", 1999, "https://www.freebuddhistaudio.com/m/medium/XeougS4OEKle.jpg"),
        Entry("LOC1023", "Bodhisattva Ideal: Wisdom and Compassion in Buddhism - Part 4, The", 1999, "https://www.freebuddhistaudio.com/m/medium/XeougS4OEKle.jpg"),
        Entry("LOC1024", "Bodhisattva Ideal: Wisdom and Compassion in Buddhism - Part 5, The", 1999, "https://www.freebuddhistaudio.com/m/medium/XeougS4OEKle.jpg"),
        Entry("LOC1025", "Bodhisattva Ideal: Wisdom and Compassion in Buddhism - Part 6, The", 1999, "https://www.freebuddhistaudio.com/m/medium/XeougS4OEKle.jpg"),
        Entry("LOC1027", "Bodhisattva Ideal: Wisdom and Compassion in Buddhism - Part 7, The", 1999, "https://www.freebuddhistaudio.com/m/medium/XeougS4OEKle.jpg"),
        Entry("LOC1026", "Bodhisattva Ideal: Wisdom and Compassion in Buddhism - Part 8, The", 1999, "https://www.freebuddhistaudio.com/m/medium/XeougS4OEKle.jpg"),
        Entry("193", "Communicating the Dharma", 1999, "https://www.freebuddhistaudio.com/images/talks/193.jpg"),
        Entry("LOC1469", "Das wahre Wunder - Buddhismus Und Menschliche Wandlung", 1999, "https://www.freebuddhistaudio.com/m/uKp8bNgbigXw.jpg"),
        Entry("LOC2124", "Gemeinsam leben und arbeiten", 1999, "https://www.freebuddhistaudio.com/m/uKp8bNgbigXw.jpg"),
        Entry("190", "Life for the Dharma, A", 1999, "https://www.freebuddhistaudio.com/images/talks/190.jpg"),
        Entry("194", "Looking Ahead a Little Way", 1999, "https://www.freebuddhistaudio.com/images/talks/194.jpg"),
        Entry("192", "Looking at the Bodhi Tree", 1999, "https://www.freebuddhistaudio.com/images/talks/192.jpg"),
        Entry("LOC1411", "Sehen wie die Dinge sind", 1999, "https://www.freebuddhistaudio.com/m/uKp8bNgbigXw.jpg"),
        Entry("191", "Standing on Holy Ground", 1999, "https://www.freebuddhistaudio.com/images/talks/191.jpg"),
        Entry("S01", "Readings from the Pali Canon", 2000, "https://www.freebuddhistaudio.com/m/medium/95Fw8s3taQ29.jpg"),
        Entry("LOC991", "What Is the Dharma? The Essential Teachings of the Buddha - Part 1", 2000, "https://www.freebuddhistaudio.com/m/medium/kQOmxNpYrAT7.jpg"),
        Entry("LOC994", "What Is the Dharma? The Essential Teachings of the Buddha - Part 2", 2000, "https://www.freebuddhistaudio.com/m/medium/kQOmxNpYrAT7.jpg"),
        Entry("LOC995", "What Is the Dharma? The Essential Teachings of the Buddha - Part 3", 2000, "https://www.freebuddhistaudio.com/m/medium/kQOmxNpYrAT7.jpg"),
        Entry("LOC997", "What Is the Dharma? The Essential Teachings of the Buddha - Part 4", 2000, "https://www.freebuddhistaudio.com/m/medium/kQOmxNpYrAT7.jpg"),
        Entry("LOC998", "What Is the Dharma? The Essential Teachings of the Buddha - Part 5", 2000, "https://www.freebuddhistaudio.com/m/medium/kQOmxNpYrAT7.jpg"),
        Entry("LOC999", "What Is the Dharma? The Essential Teachings of the Buddha - Part 6", 2000, "https://www.freebuddhistaudio.com/m/medium/kQOmxNpYrAT7.jpg"),
        Entry("LOC1000", "What Is the Dharma? The Essential Teachings of the Buddha - Part 7", 2000, "https://www.freebuddhistaudio.com/m/medium/kQOmxNpYrAT7.jpg"),
        Entry("196", "Footsteps of Delight", 2001, "https://www.freebuddhistaudio.com/images/talks/196.jpg"),
        Entry("198", "Fields of Creativity", 2002, "https://www.freebuddhistaudio.com/images/talks/198.jpg"),
        Entry("197", "Six Distinctive Emphases of the FWBO, The", 2002, "https://www.freebuddhistaudio.com/images/talks/197.jpg"),
        Entry("LOC939", "Who Is the Buddha? - Part 1", 2002, "https://www.freebuddhistaudio.com/m/medium/WeJXafwhHkVR.jpg"),
        Entry("LOC941", "Who Is the Buddha? - Part 2", 2002, "https://www.freebuddhistaudio.com/m/medium/WeJXafwhHkVR.jpg"),
        Entry("LOC942", "Who Is the Buddha? - Part 3", 2002, "https://www.freebuddhistaudio.com/m/medium/WeJXafwhHkVR.jpg"),
        Entry("LOC944", "Who Is the Buddha? - Part 4", 2002, "https://www.freebuddhistaudio.com/m/medium/WeJXafwhHkVR.jpg"),
        Entry("LOC943", "Who Is the Buddha? - Part 5", 2002, "https://www.freebuddhistaudio.com/m/medium/WeJXafwhHkVR.jpg"),
        Entry("LOC1016", "Living with Awareness (A Guide to the Satipatthana Sutta) - Part 1", 2003, "https://www.freebuddhistaudio.com/m/medium/kjQk2xrOMnvq.jpg"),
        Entry("LOC1017", "Living with Awareness (A Guide to the Satipatthana Sutta) - Part 2", 2003, "https://www.freebuddhistaudio.com/m/medium/kjQk2xrOMnvq.jpg"),
        Entry("LOC1019", "Living with Awareness (A Guide to the Satipatthana Sutta) - Part 3", 2003, "https://www.freebuddhistaudio.com/m/medium/kjQk2xrOMnvq.jpg"),
        Entry("LOC1018", "Living with Awareness (A Guide to the Satipatthana Sutta) - Part 4", 2003, "https://www.freebuddhistaudio.com/m/medium/kjQk2xrOMnvq.jpg"),
        Entry("Q01", "Evening with Sangharakshita: Questions and Answers with the Sangha, An", 2004, "https://www.freebuddhistaudio.com/m/medium/cEGnqLBZh9Xb.jpg"),
        Entry("LOC1009", "Living with Kindness  (The Buddha's Teaching on Metta) - Part 4", 2004, "https://www.freebuddhistaudio.com/m/medium/oAqO4vKtysQI.jpg"),
        Entry("LOC1007", "Living with Kindness (The Buddha's Teaching on Metta) - Part 1", 2004, "https://www.freebuddhistaudio.com/m/medium/oAqO4vKtysQI.jpg"),
        Entry("LOC1008", "Living with Kindness (The Buddha's Teaching on Metta) - Part 2", 2004, "https://www.freebuddhistaudio.com/m/medium/oAqO4vKtysQI.jpg"),
        Entry("LOC1010", "Living with Kindness (The Buddha's Teaching on Metta) - Part 3", 2004, "https://www.freebuddhistaudio.com/m/medium/oAqO4vKtysQI.jpg"),
        Entry("BH09", "Remembering Ambedkar", 2006, "https://www.freebuddhistaudio.com/images/talks/BH09.jpg"),
        Entry("LOC1001", "Yogi's Joy: Songs of Milarepa - Part 1, The", 2006, "https://www.freebuddhistaudio.com/m/medium/ZX1r8xRjDnkd.jpg"),
        Entry("LOC1002", "Yogi's Joy: Songs of Milarepa - Part 2, The", 2006, "https://www.freebuddhistaudio.com/m/medium/ZX1r8xRjDnkd.jpg"),
        Entry("LOC1003", "Yogi's Joy: Songs of Milarepa - Part 3, The", 2006, "https://www.freebuddhistaudio.com/m/medium/ZX1r8xRjDnkd.jpg"),
        Entry("LOC1004", "Yogi's Joy: Songs of Milarepa - Part 4, The", 2006, "https://www.freebuddhistaudio.com/m/medium/ZX1r8xRjDnkd.jpg"),
        Entry("LOC1005", "Yogi's Joy: Songs of Milarepa - Part 5, The", 2006, "https://www.freebuddhistaudio.com/m/medium/ZX1r8xRjDnkd.jpg"),
        Entry("LOC1006", "Yogi's Joy: Songs of Milarepa - Part 6, The", 2006, "https://www.freebuddhistaudio.com/m/medium/ZX1r8xRjDnkd.jpg"),
        Entry("LOC251", "Buddha's Enlightenment, The", 2007, "https://www.freebuddhistaudio.com/m/uKp8bNgbigXw.jpg"),
        Entry("BH11", "Entering the Sangha", 2007, "https://www.freebuddhistaudio.com/m/medium/0OyI8DbYOROw.jpg"),
        Entry("IV02", "In Retrospect: A Conversation With Sangharakshita", 2007, "https://www.freebuddhistaudio.com/m/medium/R0RhVPvQsIyN.jpg"),
        Entry("BH10", "Looking Back - And Forward", 2007, "https://www.freebuddhistaudio.com/m/medium/dSe4C2sfN5TF.jpg"),
        Entry("BH13", "On Tara", 2007, "https://www.freebuddhistaudio.com/images/talks/BH13.jpg"),
        Entry("LOC851", "Precious Teachers (Indian Memoirs of an English Buddhist) - Part 1", 2007, "https://www.freebuddhistaudio.com/m/medium/B2z6RslVk8Vj.jpg"),
        Entry("LOC850", "Precious Teachers (Indian Memoirs of an English Buddhist) - Part 2", 2007, "https://www.freebuddhistaudio.com/m/medium/B2z6RslVk8Vj.jpg"),
        Entry("LOC852", "Precious Teachers (Indian Memoirs of an English Buddhist) - Part 3", 2007, "https://www.freebuddhistaudio.com/m/medium/B2z6RslVk8Vj.jpg"),
        Entry("LOC853", "Precious Teachers (Indian Memoirs of an English Buddhist) - Part 4", 2007, "https://www.freebuddhistaudio.com/m/medium/B2z6RslVk8Vj.jpg"),
        Entry("LOC854", "Precious Teachers (Indian Memoirs of an English Buddhist) - Part 5", 2007, "https://www.freebuddhistaudio.com/m/medium/B2z6RslVk8Vj.jpg"),
        Entry("BH12", "Recollections and Reflections on My Going Forth", 2007, "https://www.freebuddhistaudio.com/images/talks/BH12.jpg"),
        Entry("LOC491", "Die sechs besonderen Merkmale des FWBO", 2008, "https://www.freebuddhistaudio.com/m/uKp8bNgbigXw.jpg"),
        Entry("LOC110", "Dreams and Rebirth", 2008, "https://www.freebuddhistaudio.com/images/talks/LOC110.jpg"),
        Entry("BH14", "Forty Years On - The Six Emphases of the FWBO", 2008, "https://www.freebuddhistaudio.com/images/talks/BH14.jpg"),
        Entry("LOC44", "Growing the Spiritual Community", 2008, "https://www.freebuddhistaudio.com/images/talks/LOC44.jpg"),
        Entry("LOC874", "Living with Kindness - Part 1", 2008, "https://www.freebuddhistaudio.com/m/uKp8bNgbigXw.jpg"),
        Entry("LOC875", "Living with Kindness - Part 2", 2008, "https://www.freebuddhistaudio.com/m/uKp8bNgbigXw.jpg"),
        Entry("LOC877", "Living with Kindness - Part 3", 2008, "https://www.freebuddhistaudio.com/m/uKp8bNgbigXw.jpg"),
        Entry("LOC876", "Living with Kindness - Part 4", 2008, "https://www.freebuddhistaudio.com/m/uKp8bNgbigXw.jpg"),
        Entry("DE03", "FWBO and the Path of Spiritual Development, The", 2009, "https://www.freebuddhistaudio.com/images/talks/DE03.jpg"),
        Entry("BH16", "Launch of The Essential Sangharakshita and Living Ethically", 2009, "https://www.freebuddhistaudio.com/images/talks/BH16.jpg"),
        Entry("LOC1011", "Living Ethically (Advice from Nagarjuna's Precious Garland) - Part 1", 2009, "https://www.freebuddhistaudio.com/m/medium/SGZhkIrcsvya.jpg"),
        Entry("LOC1012", "Living Ethically (Advice from Nagarjuna's Precious Garland) - Part 2", 2009, "https://www.freebuddhistaudio.com/m/medium/SGZhkIrcsvya.jpg"),
        Entry("LOC1013", "Living Ethically (Advice from Nagarjuna's Precious Garland) - Part 3", 2009, "https://www.freebuddhistaudio.com/m/medium/SGZhkIrcsvya.jpg"),
        Entry("LOC1014", "Living Ethically (Advice from Nagarjuna's Precious Garland) - Part 4", 2009, "https://www.freebuddhistaudio.com/m/medium/SGZhkIrcsvya.jpg"),
        Entry("LOC1015", "Living Ethically (Advice from Nagarjuna's Precious Garland) - Part 5", 2009, "https://www.freebuddhistaudio.com/m/medium/SGZhkIrcsvya.jpg"),
        Entry("BH17", "Living with Ethics", 2009, "https://www.freebuddhistaudio.com/images/talks/BH17.jpg"),
        Entry("LOC836", "Sangharakshita Launches The Essential Sangharakshita and Living Ethically", 2009, "https://www.freebuddhistaudio.com/m/uKp8bNgbigXw.jpg"),
        Entry("LOC431", "Looking Back - and Forward, Sangharakshita Speaks to the European Order Weekend", 2010, "https://www.freebuddhistaudio.com/m/uKp8bNgbigXw.jpg"),
        Entry("LOC848", "Religion of Art - Part 1, The", 2011, "https://www.freebuddhistaudio.com/m/medium/tguJkUQdjCJz.jpg"),
        Entry("LOC849", "Religion of Art - Part 2, The", 2011, "https://www.freebuddhistaudio.com/m/medium/tguJkUQdjCJz.jpg"),
        Entry("BH18", "Mingling Souls - Launching Dear Dinoo, Letters to a Friend", 2012, "https://www.freebuddhistaudio.com/images/talks/BH18.jpg"),
        Entry("LOC3973", "Beating the Drum: Maha Bodhi Editorials, 1954-64", 2019, "https://www.freebuddhistaudio.com/m/medium/6Q8CsHOtrQ6A.jpg"),
        Entry("LOC3789", "Buddha Mind", 2019, "https://www.freebuddhistaudio.com/m/medium/yH7D06h9jMvW.jpg"),
        Entry("LOC3974", "Early Writings 1944-1954", 2019, "https://www.freebuddhistaudio.com/m/medium/8ErYT2vN0rZJ.jpg"),
        Entry("LOC3800", "Facing Mount Kanchenjunga: An English Buddhist in the Eastern Himalayas - Part 1", 2019, "https://www.freebuddhistaudio.com/m/medium/tFKj6rjoRPcF.jpg"),
        Entry("LOC3801", "Facing Mount Kanchenjunga: An English Buddhist in the Eastern Himalayas - Part 2", 2019, "https://www.freebuddhistaudio.com/m/medium/tFKj6rjoRPcF.jpg"),
        Entry("LOC3802", "Facing Mount Kanchenjunga: An English Buddhist in the Eastern Himalayas - Part 3", 2019, "https://www.freebuddhistaudio.com/m/medium/tFKj6rjoRPcF.jpg"),
        Entry("LOC3803", "Facing Mount Kanchenjunga: An English Buddhist in the Eastern Himalayas - Part 4", 2019, "https://www.freebuddhistaudio.com/m/medium/tFKj6rjoRPcF.jpg"),
        Entry("LOC3804", "Facing Mount Kanchenjunga: An English Buddhist in the Eastern Himalayas - Part 5", 2019, "https://www.freebuddhistaudio.com/m/medium/tFKj6rjoRPcF.jpg"),
        Entry("LOC3805", "Facing Mount Kanchenjunga: An English Buddhist in the Eastern Himalayas - Part 6", 2019, "https://www.freebuddhistaudio.com/m/medium/tFKj6rjoRPcF.jpg"),
        Entry("LOC3883", "From Genesis to the Diamond Sutra: A Western Buddhist's Encounters with Christianity", 2019, "https://www.freebuddhistaudio.com/m/uKp8bNgbigXw.jpg"),
        Entry("LOC3882", "Inconceivable Emancipation: Themes from the Vimalakirti Nirdesha, The", 2019, "https://www.freebuddhistaudio.com/m/medium/I2yd0MO71NPT.jpg"),
        Entry("LOC3814", "Moving Against the Stream: The Birth of a New Buddhist Movement  - Part 2", 2019, "https://www.freebuddhistaudio.com/m/medium/eFe7p0cOx009.jpg"),
        Entry("LOC3815", "Moving Against the Stream: The Birth of a New Buddhist Movement  - Part 3", 2019, "https://www.freebuddhistaudio.com/m/medium/eFe7p0cOx009.jpg"),
        Entry("LOC3816", "Moving Against the Stream: The Birth of a New Buddhist Movement  - Part 4", 2019, "https://www.freebuddhistaudio.com/m/medium/eFe7p0cOx009.jpg"),
        Entry("LOC3817", "Moving Against the Stream: The Birth of a New Buddhist Movement  - Part 5", 2019, "https://www.freebuddhistaudio.com/m/medium/eFe7p0cOx009.jpg"),
        Entry("LOC3818", "Moving Against the Stream: The Birth of a New Buddhist Movement  - Part 6", 2019, "https://www.freebuddhistaudio.com/m/medium/eFe7p0cOx009.jpg"),
        Entry("LOC3813", "Moving Against the Stream: The Birth of a New Buddhist Movement - Part 1", 2019, "https://www.freebuddhistaudio.com/m/medium/eFe7p0cOx009.jpg"),
        Entry("LOC3858", "Survey of Buddhism: Its Doctrines and Methods Through the Ages - Chapter 2, A", 2019, "https://www.freebuddhistaudio.com/m/medium/sat8PgTkJsGK.jpg"),
    )

    /** Fix titles where 'The/A/An' has been moved to the end for sorting. */
    private fun fixTitle(title: String): String = when {
        title.endsWith(", The") -> "The " + title.dropLast(5)
        title.endsWith(", A") -> "A " + title.dropLast(3)
        title.endsWith(", An") -> "An " + title.dropLast(4)
        else -> title
    }

    fun allTalksAsSearchResults(): List<SearchResult> = entries.map { e ->
        SearchResult(
            catNum = e.catNum,
            title = fixTitle(e.title),
            speaker = "Sangharakshita",
            imageUrl = e.imageUrl,
            path = "https://www.freebuddhistaudio.com/audio/details?num=\${e.catNum}",
            year = e.year,
        )
    }

    data class Series(val id: String, val title: String)

    val series: List<Series> = listOf(
        Series("X01", "Introducing the Three Jewels of Buddhism"),
        Series("X02", "The Meaning of Conversion in Buddhism"),
        Series("X03", "The Essence of Zen"),
        Series("X04", "Introducing Buddhism"),
        Series("X05", "Ritual and Devotion in Buddhism"),
        Series("X06", "Aspects of Buddhist Psychology"),
        Series("X07", "The Buddha's Noble Eightfold Path"),
        Series("X08", "An Introduction to Tibetan Buddhism"),
        Series("X09", "Aspects of the Bodhisattva Ideal"),
        Series("X10", "The Higher Evolution"),
        Series("X11", "Aspects of the Higher Evolution of the Individual"),
        Series("X12", "Parables, Myths and Symbols of Mahayana in the White Lotus Sutra"),
        Series("X13", "Creative Symbols of the Tantric Path to Enlightenment"),
        Series("X14", "Human Enlightenment"),
        Series("X15", "Transformation of Life and World in the Sutra of Golden Light"),
        Series("X16", "Buddhism for Today and Tomorrow"),
        Series("X17", "A New Buddhist Movement"),
        Series("X18", "Incidents from the Pali Canon"),
        Series("X19", "The Inconceivable Emancipation: Themes from the Vimalakirti Nirdesha"),
        Series("X20", "Reality, Consciousness and Order"),
        Series("X21", "The Nature of Reality: Buddhism as Transformation"),
        Series("X22", "Three Lectures to the Friends of the Western Buddhist Order"),
        Series("X238", "Lectures on the World of Images"),
    )

    fun seriesAsBrowseCategories(): List<BrowseCategory> = series.map { s ->
        BrowseCategory(
            id = "sang_series_${s.id}",
            name = s.title,
            type = CategoryType.SERIES,
            browseUrl = "https://www.freebuddhistaudio.com/series/details?num=${s.id}",
        )
    }
}